#apps
$menu           = ~/.config/rofi/launcher/launcher.sh 
$settings       = ~/.config/rofi/settings/settings.sh
$wallpaper      = ~/.config/rofi/Wallpaper/wallpaper.sh
$bootmenu       = ~/.config/rofi/powermenu/powermenu.sh
$clipboard      = ~/.config/rofi/clipboard/clipboard.sh
$terminal       = kitty
$fileManager    = thunar
$browser        = zen-browser 
$code_editor    = nvim
$music          = spicetify apply
$notes          = obsidian
$chat           = elecwhat

#autostart
exec-once = awww-daemon
exec-once = waybar
exec-once = swaync
exec-once = eww-daemon
exec-once = hypridle
exec-once = swayosd-server
exec-once = nm-applet
exec-once = blueman-applet
exec-once = cliphist wipe
env = CLIPHIST_MAX_ITEMS, 500
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
