##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/
# See https://wiki.hypr.land/Configuring/Workspace-Rules/

# Ignore maximize requests from all apps
windowrule {
    name       = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name            = fix-xwayland-drags
    match:class     = ^$
    match:title     = ^$
    match:xwayland  = true
    match:float     = true
    match:fullscreen = false
    match:pin       = false

    no_focus = true
}

# hyprland-run floating terminal (bottom-left)
windowrule {
    name        = move-hyprland-run
    match:class = hyprland-run

    move  = 20 monitor_h-120
    float = yes
}

#for spotify 
xwayland {

force_zero_scaling = true

}
